using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MinioCommon
{
    /// <summary>
    /// Root model for the single config.json file.
    ///
    /// Migrated from Newtonsoft.Json to System.Text.Json with source generation
    /// (see <see cref="AppJsonContext"/> below) so that:
    ///   - Loading requires **zero reflection** at runtime.
    ///   - The project remains compatible with trimming and AOT if we ever enable them.
    ///   - Property names are case-insensitive (Bcl default) to keep tolerating
    ///     user-written config.json in either case.
    ///
    /// Marked <c>partial</c> so that the System.Text.Json source generator
    /// can attach generated metadata to this type without modifying it.
    /// </summary>
    public partial class ConfigFile
    {
        /// <summary>Config file schema version. Currently 1.</summary>
        public int Version { get; set; }

        /// <summary>
        /// Named MinIO connection profiles.
        /// Each config in Configs can reference a profile by name via MinIOProfile field.
        /// </summary>
        public Dictionary<string, MinIOProfile> MinIOProfiles { get; set; }

        /// <summary>
        /// SMTP email settings for sending failure alerts.
        /// When null, no email notifications are sent.
        /// </summary>
        public EmailSettings Email { get; set; }

        /// <summary>List of sync task configurations.</summary>
        public List<SyncConfig> Configs { get; set; }
    }

    /// <summary>
    /// Compile-time JSON metadata for <see cref="ConfigFile"/> and all transitively
    /// referenced types (<see cref="SyncConfig"/>, <c>string[]</c> properties).
    ///
    /// Generated by the System.Text.Json source generator at build time;
    /// no runtime reflection is needed to deserialize. This unlocks future
    /// trimming/AOT compatibility and brings a modest start-up speedup.
    ///
    /// Internal because it is only consumed within this assembly by
    /// <see cref="ConfigManager"/>.
    /// </summary>
    [JsonSourceGenerationOptions(
        WriteIndented = true,
        // No PropertyNamingPolicy set intentionally: the existing config.json shipped
        // with the project uses PascalCase keys (Version, Id, LocalFolderPath, etc.).
        // Forcing CamelCase would silently break every user-written config.
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonSerializable(typeof(ConfigFile))]
    [JsonSerializable(typeof(SyncConfig))]
    [JsonSerializable(typeof(MinIOProfile))]
    [JsonSerializable(typeof(EmailSettings))]
    [JsonSerializable(typeof(Dictionary<string, MinIOProfile>))]
    internal partial class AppJsonContext : JsonSerializerContext
    {
    }
}
